---
apiVersion: v2
name: zookeeper-operator
version: <version_placeholder>
appVersion: "<version_placeholder>"

home: https://github.com/stackabletech/zookeeper-operator

maintainers:
  - name: Stackable
    url: https://www.stackable.tech
