---
apiVersion: v2
name: zookeeper-operator
version: 0.9.0-nightly
appVersion: "0.9.0-nightly"
home: https://github.com/stackabletech/zookeeper-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
